### ISSUE TITLE
Unable to get location info

### ISSUE THREAD

**Issue by jahansha** [SmartableAI/developer-program#7]
I am unable to get location info:
I tried:
http://api.smartable.ai/coronavirus/stats?isoCode=IT  etc.
Can anyone please provide the format to GET location info.

Thanks

**Comment by SmartableAI** [comment]
Hi 
The API request url format is https://api.smartable.ai/coronavirus/stats/{location}.  In your case, you should query  https://api.smartable.ai/coronavirus/stats/IT

Please also note that if you directly hit the above URL, you will get an unauthorized error. That's because you need to attach the (free) API key to the http request header.  You can find code examples from our tryit experience in the developer portal.  Here is the documentation: https://developer.smartable.ai/api-details#api=coronavirus&operation=stats

Please feel free to let me know if you have any other questions. 

Thanks
Scott

**Comment by jahansha** [comment]
Thanks for getting back. It is all working now.


Sent from Yahoo Mail for iPad


On Wednesday, March 25, 2020, 10:52 AM, Smartable AI <notifications@github.com> wrote:




Hi
The API request url format is https://api.smartable.ai/coronavirus/stats/{location}. In your case, you should query https://api.smartable.ai/coronavirus/stats/IT

Please also note that if you directly hit the above URL, you will get an unauthorized error. That's because you need to attach the (free) API key to the http request header. You can find code examples from our tryit experience in the developer portal. Here is the documentation: https://developer.smartable.ai/api-details#api=coronavirus&operation=stats

Please feel free to let me know if you have any other questions.

Thanks
Scott
